# Generated by Django 5.2.6 on 2025-09-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasktracker", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="id",
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
