# Generated by Django 5.2.6 on 2025-10-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasktracker", "0004_alter_task_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="reminder_sent",
            field=models.BooleanField(
                default=False, verbose_name="Напоминание отправлено"
            ),
        ),
    ]
