# Generated by Django 5.2.6 on 2025-10-02 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasktracker", "0005_task_reminder_sent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="reminder_sent",
        ),
    ]
