# Generated by Django 5.2.6 on 2025-09-30 11:55

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(default=users.models.generate_ulid, editable=False),
        ),
    ]
